FROM golang:1.18-buster as build

WORKDIR /base
ADD . /base/
RUN go build -o /base/app ./cmd/airbyte

FROM gcr.io/distroless/base-debian10:debug
COPY --from=build /base/app /base/app

ENTRYPOINT ["/base/app"]

#docker build -t airbyte/airbyte-shopify-source:dev -f dockerfile-airbyte-shopify .
#docker run --rm airbyte/airbyte-shopify-source:dev